### ISSUE TITLE
Package.json dependency fails to download due to port-blocking

### ISSUE THREAD

**Issue by pfraze** [ssbc/ssb-keys#21]
%F3KYKbLCXF/q/k54GN0QxwnM8MLgvJxBYRVEnDd/744=.sha256

> This ssb-keys dependency is causing us a lot of problems in our university network, only because it forces npm into pulling it through native git protocol which is TCP 9418. Could we maybe make it git+ssh:// or https://?

> You would think a technical university would know better than running a whitelist outbound firewall and blocking icmp but hey.... </1stworldproblem>

**Comment by dominictarr** [comment]
we don't really want ecc.js anyway. lets just kill that dep. that was only there so we didn't have to remove tests.
