### ISSUE TITLE
SyntaxError in strict mode when importing into es6

### ISSUE THREAD

**Issue by gardner** [ssbc/ssb-keys#33]
node: v6.9.3
npm: 3.10.10

Trying to import ssb-keys into React Native.

    npm install -g react-native-cli
    git clone https://github.com/gardner/rnssb.git
    cd rnssb
    npm install
    react-native run-android

![simulator screen shot jan 26 2017 11 12 12 am](https://cloud.githubusercontent.com/assets/787026/22341920/563c9eb8-e3b8-11e6-925c-43ff1742422d.png)

**Comment by dominictarr** [comment]
why are you exporting into strict mode? is that a react-native thing?

**Comment by gardner** [comment]
Yeah, react native uses the [react-native](https://github.com/facebook/react-native/tree/master/babel-preset) preset. You can see the code here: https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js

It's weird because the `react-native` preset seems to turn off strict for commonjs modules:
`['transform-es2015-modules-commonjs', { strict: false, allowTopLevelThis: true }],`

I logged this issue here in case there's any future-proofing to be done on ssb-keys. Please close this issue if there is none. I'll keep iterating on a fix. It's probably a setting that recently changed in react-native. Thanks! ⛵⛵⛵

**Comment by dominictarr** [comment]
actually, this was a simple fix. ssb-keys@7.0.4 now uses strict mode!
