### ISSUE TITLE
storage.js does not work with webpack

### ISSUE THREAD

**Issue by mlegore** [ssbc/ssb-keys#40]
I get the following error when attempting to use ssb-keys 7.0.10

    ERROR in ./node_modules/ssb-keys/storage.js
    Module not found: Error: Can't resolve './eccjs' in '/<removed>/node_modules/ssb-keys'
     @ ./node_modules/ssb-keys/storage.js 72:14-40
     @ ./node_modules/ssb-keys/index.js
     @ ./src/main/ssb/ssb-config.js
     @ ./src/main/index.js

**Comment by dominictarr** [comment]
fixed in 7.0.11
