### ISSUE TITLE
keys structure [question] 

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-keys#42]
Hello. Is the documentation out of date? It looks like it is missing the field `curve`.

```js
//usually, load keys like this
var keys = ssbkeys.loadOrCreateSync(filename)
/* => {
  id: String,
  public: String,
  private: String
}*/
```

but there is also `curve: 'ed25519'`

Also, what is the `id` field? a random string to identify this key pair?

**Comment by evbogue** [comment]
@nichoth id is the same as public, but with an @ sign in front of it. It's always seemed a little redundant to me. Perhaps we could deprecate id someday and instead have ssbkey.id return public with a prepended @ sign?

And yes, curve is specified in secret files.

**Comment by dominictarr** [comment]
id is the ssb id, which has the `@` and curve type combined. We currently only have one supported signature algorithm, so the curve field isn't very useful, but will be when we need to support another.
