### ISSUE TITLE
When persisting, `key` is encoded with base64 twice

### ISSUE THREAD

**Issue by the-kenny** [ssbc/ssb-keys#47]
`keysToJSON` calls `tag(key.toString('base64'), curve)` and `tag` calls `key.toString(base64)` again. This isn't a big issue in itself but might be confusing at some later point when the code gets refactored.

https://github.com/ssbc/ssb-keys/blob/master/util.js#L29

**Comment by the-kenny** [comment]
Correction: It isn't encoded twice, as `toString` on `String` is just a no-op. It's still unclear and clearly not intended :-)

**Comment by davegomez** [comment]
I don't think this is a bug because there is no double encoding happening here.

I think the confusion comes from a function call `tag` that besides doing its job, to tag the input, it's also encoding it, which a different function should do.
