### ISSUE TITLE
asynchronous methods

### ISSUE THREAD

**Issue by substack** [ssbc/ssb-keys#5]
I want to build a version of this module that will work with [keyboot](https://npmjs.org/package/keyboot), but the underlying [browser crypto methods](http://msdn.microsoft.com/en-us/library/ie/dn302321%28v=vs.85%29.aspx) are all asynchronous and the messages travel over an asynchronous postMessage rpc bridge too.

However, the current interface is synchronous.

**Comment by dominictarr** [comment]
yeah, this will require rewriting the validation in secure-scuttlebutt and a few other places - it's still last call on the webcrypto api so I asked them why not just make the api sync.

**Comment by dominictarr** [comment]
that said, it will be easier to support async than to wait for the webcrypto api to change.
