### ISSUE TITLE
can't work in browser ?

### ISSUE THREAD

**Issue by helxsz** [ssbc/ssb-keys#57]
I am playing ssb-keys on the browser along with angular stack, but both ssb-keys and private-box depends on chloride library, and chloride library can not work on the browser.

how would i make it work

**Comment by ahdinosaur** [comment]
> chloride library can not work on the browser.

hi @helxsz, [`chloride`](https://github.com/dominictarr/chloride) should be able to work in the browser, can you post the error you're seeing?

**Comment by ahdinosaur** [comment]
but it might be that `chloride` doesn't work in the browser unless you're using [`browserify`](https://github.com/browserify/browserify/), i could see some possible awkwardness with other bundlers from how [`chloride/index.js`](https://github.com/dominictarr/chloride/blob/master/index.js) does the browser loading.

**Comment by helxsz** [comment]
yes, my wrong, chloride does work. What doesn't work is

**Comment by ahdinosaur** [comment]
@helxsz: let's move this discussion to https://github.com/dominictarr/chloride/issues/12, i also made a pull request that might help: https://github.com/dominictarr/chloride/pull/13

**Comment by dominictarr** [comment]
@helxsz what command are you running that produces that error?

**Comment by helxsz** [comment]
@ahdinosaur @dominictarr the new pull request works out directly, thanks for the work !!
